#!/usr/bin/php
<?php

$path = pathinfo($_SERVER["_"])["dirname"];
include($path.'/ini-parser');

//-----------------------------------------------------------

$data = isset($argv[1]) ? $argv[1] : "0";
if(array_key_exists($remote, $robot)){
	echo $Bold."[$remote]$endBold --- Building the sources.\n";
	system("ssh -tt eros@$robot[$remote] $path/../$platform/build.sh $data");
}
else
	echo $Bold."[Error]$endBold --- Robot dengan nama $platform tidak ada.\n";
