#!/usr/bin/php
<?php
$file_handle = fopen("robot.ini", "r");
while (!feof($file_handle) ) {
	$line_of_text = fgets($file_handle);
	$parts = explode('=', $line_of_text);
	if ($parts[0]!=NULL)
		$robot[$parts[0]]=substr($parts[1],0,strlen($parts[1])-1);
}
fclose($file_handle);

$remote=file_get_contents("myrobot.ini");
$remote=substr($remote,0,strlen($remote));
//-----------------------------------------------------------
$DATE=date('Y-m-d G:i:s');
$input = isset($argv[1]) ? $argv[1] : "";
if(array_key_exists($remote, $robot)){
	echo "# Updating Date $remote..\n";
	system("ssh $remote 'sudo date --set \"$DATE\"'");
	echo "# Checkup $remote..\n";
	system("ssh -tt eros@$robot[$remote] ./env/checkup.sh $input");
}
else
	echo "# The robot doesnt exist..\n";
