#!/usr/bin/php
<?php

$path = pathinfo($_SERVER["_"])["dirname"];
include($path.'/ini-parser');

//-----------------------------------------------------------

$input = isset($argv[1]) ? $argv[1] : "";
if(array_key_exists($remote, $robot)){
	echo $Bold."[$remote]$endBold --- Editting $input.\n";
	system("ssh eros@$robot[$remote] $path/../$platform/editor.sh $input");
}
else
	echo $Bold."[Error]$endBold --- Robot dengan nama $platform tidak ada.\n";
