#!/usr/bin/php
<?php

$path = pathinfo($_SERVER["_"])["dirname"];
include($path.'/ini-parser');

//-----------------------------------------------------------
$input = isset($argv[1]) ? $argv[1] : "";
if(array_key_exists($remote, $robot) && array_key_exists($platform, $workspace)){
	echo $Bold."[$remote]$endBold --- Running Game Controller.\n";
	system($path."/GameController/GameController-master/build/jar/start_kid.bash");
} else echo $Bold."[Error]$endBold --- Robot dengan nama $remote tidak ada.\n";
