#!/usr/bin/php
<?php

$path = pathinfo($_SERVER["_"])["dirname"];
include($path.'/ini-parser');

//-----------------------------------------------------------

#$input = isset($argv[1]) ? $argv[1] : "0";
if(array_key_exists($remote, $robot)){
	system("ssh -tt eros@$robot[$remote] -X -Y $path/../$platform/guvc.sh");
}
else
	echo $Bold."[Error]$endBold --- Robot dengan nama $remote tidak ada.\n";
