#!/usr/bin/php
<?php

$path = pathinfo($_SERVER["_"])["dirname"];
include($path.'/ini-parser');

//-----------------------------------------------------------

if(array_key_exists($remote, $robot)){
	echo "Compiling";
	system("ssh -tt eros@$robot[$remote] ~/remote/make.sh $platform $workspace[$platform]");
}
else echo $Bold."[Error]$endBold --- Robot dengan nama $remote tidak ada.\n";
