#!/usr/bin/php
<?php

$path = pathinfo($_SERVER["_"])["dirname"];
include($path.'/ini-parser');

//-----------------------------------------------------------

if(array_key_exists($remote, $robot)){
	echo "Compiling";
	system("ssh -tt eros@$robot[$remote] $path/../$platform/make.sh");
}
else echo "\033[1m## The robot doesnt exist..\n";
