#!/usr/bin/php
<?php

$path = pathinfo($_SERVER["_"])["dirname"];
include($path.'/ini-parser');

//-----------------------------------------------------------

$input = isset($argv[1]) ? $argv[1] : "";
if(array_key_exists($remote, $robot) && array_key_exists($platform, $workspace)){
	echo $Bold."[$remote]$endBold --- Opening Monitor.\n";
	system($path."/monitor.sh $platform $workspace[$platform] $input");
} else echo $Bold."[Error]$endBold --- Robot dengan nama $remote tidak ada.\n";
