#!/usr/bin/php
<?php

$path = pathinfo($_SERVER["_"])["dirname"];
include($path.'/ini-parser');

//-----------------------------------------------------------
if(array_key_exists($remote, $robot)){
	echo $Bold."[$remote]$endBold --- Setting network.\n";
	system("ssh -tt eros@$robot[$remote] $path/../$platform/net.sh $remote");
}
else
	echo $Bold."[Error]$endBold --- Robot dengan nama $platform tidak ada.\n";
