#!/usr/bin/php
<?php

$path = pathinfo($_SERVER["_"])["dirname"];
include($path.'/ini-parser');

//-----------------------------------------------------------

$input = isset($argv[1]) ? $argv[1] : "";
if(array_key_exists($remote, $robot)){
	echo "# Setting $remote..\n";
	system("ssh eros@$robot[$remote] $path/../$platform/param.sh");
}
else
	echo "# The robot doesnt exist..\n";
