#!/usr/bin/php
<?php

$path = pathinfo($_SERVER["_"])["dirname"];
include($path.'/ini-parser');

//-----------------------------------------------------------

$input = isset($argv[1]) ? $argv[1] : "";
if(array_key_exists($remote, $robot)){
	echo $Bold."[$remote]$endBold --- Setting $remote..\n";
	system("ssh eros@$robot[$remote] $path/../$platform/param.sh");
}
else
	echo $Bold."[Error]$endBold --- Robot dengan nama $remote tidak ada.\n";
