#!/usr/bin/php
<?php

$path = pathinfo($_SERVER["_"])["dirname"];
include($path.'/ini-parser');

//-------------------------------------------------------

if(array_key_exists($remote, $robot)){
	echo $Bold."[$remote]$endBold --- Pinging robot.\n";
	system("ping $robot[$remote]");
}
else
	echo $Bold."[Error]$endBold --- Robot dengan nama $remote tidak ada.\n";
