#!/usr/bin/php
<?php

$path = pathinfo($_SERVER["_"])["dirname"];
include($path.'/ini-parser');

//-----------------------------------------------------------

$input = isset($argv[1]) ? $argv[1] : "";
if(array_key_exists($remote, $robot)){
	echo "[$remote] Starting Pixel Debugging.\n";
		system("./pixeldebug/build-pixeldebug-Desktop-Debug/pixeldebug");
}
else
	echo "[error] The robot doesnt exist.\n";
