#!/usr/bin/php
<?php

const $Bold = "\033[1m";
const $endBold = "\033[0m";

// Buka file robot.ini sebagai mode baca
$file_handle = fopen("robot.ini", "r");

// Baca per baris sampai akhir file
while (!feof($file_handle) ) {
	// Ambil isi baris
	$line_of_text = fgets($file_handle);

	// Pisahkan menjadi bagian kiri dan kanan dari tanda sama dengan
	$kiri_kanan = explode('=', $line_of_text);
	
	// Jika bagian kiri tanda sama dengan (=) tidak kosong,
	// jadikan nama index pada array robot dan masukan ip nya.
	if ($kiri_kanan[0]!=NULL) $robot[$kiri_kanan[0]]=$kiri_kanan[1];
}

// Tutup file sesudah digunakan
fclose($file_handle);

// Platform kita sekarang
$platform = file_get_contents("platform.ini");

// Robot kita sekarang
$remote = file_get_contents("myrobot.ini");

//-----------------------------------------------------------

// Nama robot valid
if(array_key_exists($remote, $robot)){
	echo $Bold+"[$remote]$endBold --- Rebooting robot.\n";

	// SSH ke robot lalu jalankan perintah reboot komputer
	system("ssh eros@$robot[$remote] ./$platform/reboot.sh");
} else echo $Bold+"[Error]$endBold --- Nama robot $remote tidak ada.\n";
