#!/usr/bin/php
<?php

$path = pathinfo($_SERVER["_"])["dirname"];
include($path.'/ini-parser');

//-----------------------------------------------------------

// Nama robot valid
if(array_key_exists($remote, $robot)){
	echo $Bold+"[$remote]$endBold --- Rebooting robot.\n";

	// SSH ke robot lalu jalankan perintah reboot komputer
	system("ssh eros@$robot[$remote] $path/../$platform/reboot.sh");
} else echo $Bold."[Error]$endBold --- Robot dengan nama $remote tidak ada.\n";
