#!/usr/bin/php
<?php
$file_handle = fopen("robot.ini", "r");
while (!feof($file_handle) ) {
	$line_of_text = fgets($file_handle);
	$parts = explode('=', $line_of_text);
	if ($parts[0]!=NULL)
		$robot[$parts[0]]=substr($parts[1],0,strlen($parts[1])-1);
}
fclose($file_handle);

$remote=file_get_contents("myrobot.ini");
$remote=substr($remote,0,strlen($remote));
//-------------------------------------------------------

if(array_key_exists($remote, $robot)){
	echo "\033[1m## Running Setting Server..\n\033[0m";
	system("ssh -R 52698:localhost:52698 $robot[$remote]");
	echo "\033[1m## Setting Server stopped..\n\033[0m";
}
else
	echo "\033[1m## The robot doesnt exist..\n\033[0m";
