#!/usr/bin/php
<?php
$file_handle = fopen("robot.ini", "r");
while (!feof($file_handle) ) {
	$line_of_text = fgets($file_handle);
	$parts = explode('=', $line_of_text);
	if ($parts[0]!=NULL)
		$robot[$parts[0]]=substr($parts[1],0,strlen($parts[1])-1);
}
fclose($file_handle);

$platform = file_get_contents("platform.ini");
$remote=file_get_contents("myrobot.ini");
$remote=substr($remote,0,strlen($remote));
//-------------------------------------------------------

if(array_key_exists($remote, $robot)){
	echo $Bold."[$remote]$endBold --- Running Setting Server.\n";
	system("ssh -R 52698:localhost:52698 eros@$robot[$remote]");
	echo $Bold."[$remote]$endBold --- Setting Server stopped.\n";
}
else
	echo $Bold."[Error]$endBold --- Robot dengan nama $platform tidak ada.\n";
