#!/usr/bin/php
<?php
$file_handle = fopen("robot.ini", "r");
while (!feof($file_handle) ) {
	$line_of_text = fgets($file_handle);
	$parts = explode('=', $line_of_text);
	if ($parts[0]!=NULL)
		$robot[$parts[0]]=substr($parts[1],0,strlen($parts[1])-1);
}
fclose($file_handle);

$platform = file_get_contents("platform.ini");
$remote=file_get_contents("myrobot.ini");
$remote=substr($remote,0,strlen($remote));
//-----------------------------------------------------------

//$remote = isset($argv[1]) ? $argv[1] : "0";
if(array_key_exists($remote, $robot)){
	echo "\033[1m[$remote] Shutting down robot.\n\033[0m";
	system("ssh eros@$robot[$remote] ./$platform/shutdown.sh");
}
else
	echo "\033[1m[error] The robot doesnt exist.\n\033[0m";
