#!/usr/bin/php
<?php

$path = pathinfo($_SERVER["_"])["dirname"];
include($path.'/ini-parser');

//-----------------------------------------------------------

// Nama robot valid
if(array_key_exists($remote, $robot)){
	echo $Bold."[$remote]$endBold --- Shutting down...\n";

	// SSH ke robot lalu jalankan perintah shutdown pada komputer
	system("ssh eros@$robot[$remote] $path/../$platform/shutdown.sh");
} else echo $Bold."[Error]$endBold --- Robot dengan nama $remote tidak ada.\n";
