#!/usr/bin/php
<?php

$path = pathinfo($_SERVER["_"])["dirname"];
include($path.'/ini-parser');

//-----------------------------------------------------------

#$input = isset($argv[1]) ? $argv[1] : "0";
if(array_key_exists($remote, $robot)){
	echo $Bold."[$remote]$endBold --- Stopping platform.\n";
	system("ssh -tt eros@$robot[$remote] $path/../$platform/rosnode_killer.sh");
}
else
	echo $Bold."[Error]$endBold --- Robot dengan nama $remote tidak ada.\n";
