#!/usr/bin/php
<?php

$path = pathinfo($_SERVER["_"])["dirname"];
include($path.'/ini-parser');

//-----------------------------------------------------------

#$input = isset($argv[1]) ? $argv[1] : "0";
if(array_key_exists($remote, $robot) && array_key_exists($platform, $workspace)){
	echo $Bold."[$remote]$endBold --- Stopping platform.\n";
	system("ssh -tt eros@$robot[$remote] ~/remote/rosnode_killer.sh $platform $workspace[$platform]");
} else echo $Bold."[Error]$endBold --- Robot dengan nama $remote tidak ada.\n";
