#!/usr/bin/php
<?php
$file_handle = fopen("robot.ini", "r");
while (!feof($file_handle) ) {
	$line_of_text = fgets($file_handle);
	$parts = explode('=', $line_of_text);
	if ($parts[0]!=NULL)
		$robot[$parts[0]]=substr($parts[1],0,strlen($parts[1])-1);
}
fclose($file_handle);

$remote=file_get_contents("myrobot.ini");
$remote=substr($remote,0,strlen($remote));
//-----------------------------------------------------------
$DATE=date('Y-m-d G:i:s');
$input = isset($argv[1]) ? $argv[1] : "";
if(array_key_exists($remote, $robot)){
	echo $Bold."[$remote]$endBold --- Updating Date.\n";
	system("ssh eros@$robot[$remote] 'sudo date --set \"$DATE\"'");
}
else
	echo $Bold."[Error]$endBold --- Robot dengan nama $platform tidak ada.\n";
