#!/usr/bin/php
<?php

// const $Bold = "\033[1m";
// const $endBold = "\033[0m";

// // Buka file robot.ini sebagai mode baca
// $file_handle = fopen("robot.ini", "r");

// // Baca per baris sampai akhir file
// while (!feof($file_handle) ) {
// 	// Ambil isi baris
// 	$line_of_text = fgets($file_handle);

// 	// Pisahkan menjadi bagian kiri dan kanan dari tanda sama dengan
// 	$kiri_kanan = explode('=', $line_of_text);
	
// 	// Jika bagian kiri tanda sama dengan (=) tidak kosong,
// 	// jadikan nama index pada array robot dan masukan ip nya.
// 	if ($kiri_kanan[0]!=NULL) $robot[$kiri_kanan[0]]=$kiri_kanan[1];
// }

// // Tutup file sesudah digunakan
// fclose($file_handle);

// // Platform kita sekarang
// $platform = file_get_contents("platform.ini");

// // Robot kita sekarang
// $remote = file_get_contents("myrobot.ini");

include('./ini-parser');

//-----------------------------------------------------------

$input1 = isset($argv[1]) ? $argv[1] : "";
$input2 = isset($argv[2]) ? $argv[2] : "";

if(array_key_exists($remote, $robot)){
	switch($input1){
		case "help": system("cat ./help-text");break;
		case "shutdown": system("e-shutdown");break;
		case "reboot": system("e-reboot");break;
		case "checkup": system("e-checkup ".$input2);break;
		case "monitor": system("monitor.sh ".$remote);break;
		case "rcv": system("e-rcv ".$input2);break;
		case "rcv2": system("e-rcv2 ".$input2);break;
		case "pixel": system("e-pixel");break;
		case "map": system("e-map ".$input2);break;
		case "echo": system("e-echo");break;
		case "gc": system("e-game-controller");break;			
		case "gc2": system("e-game-controller2");break;
		case "run": system("e-run ".$input2);break;
		case "debug": system("e-debug ".$input2);break;
		case "stop": system("e-stop");break;
		case "make": system("e-make");break;
		case "build": system("e-build ".$input2);break;
		case "clean": system("e-clean ".$input2);break;
		case "ping": system("e-ping");break;
		case "edit": system("e-edit ".$input2);break;
		case "echo": system("e-echo");break;
		case "guvc": system("e-guvc");break;
		case "set":
			switch($input2){
				case "time": system("e-time");break;
				
				// -------------------------------- //
				case "vision":
				case "kepala":
				case "capture":
				case "camera":
				case "ball":
				case "calibration":
				case "focus": system("e-setting ".$input2);break;
				// -------------------------------- //
				
				case "server": system("e-server");break;
				
				// -------------------------------- //
				case "dark":
				case "light": system("e-vm_calibrate ".$input2);break;
				// -------------------------------- //
				
				case "ip": system("e-ip ");break;
				case "net": system("e-net");break;
			}
		break;
	}
} else echo "Nama robot tidak ada\n";
