#!/usr/bin/php
<?php

$path = pathinfo($_SERVER["_"])["dirname"];
include($path.'/ini-parser');

//-----------------------------------------------------------

$input1 = isset($argv[1]) ? $argv[1] : "";
$input2 = isset($argv[2]) ? $argv[2] : "";

if(array_key_exists($remote, $robot)){
	switch($input1){
		case "help": system("cat $path/help-text");break;
		case "shutdown": system($path."/e-shutdown");break;
		case "reboot": system($path."/e-reboot");break;
		case "checkup": system($path."/e-checkup ".$input2);break;
		case "monitor": system("monitor.sh ".$remote);break;
		case "rcv": system($path."/e-rcv ".$input2);break;
		case "rcv2": system($path."/e-rcv2 ".$input2);break;
		case "pixel": system($path."/e-pixel");break;
		case "map": system($path."/e-map ".$input2);break;
		case "echo": system($path."/e-echo");break;
		case "gc": system($path."/e-game-controller");break;			
		case "gc2": system($path."/e-game-controller2");break;
		case "run": system($path."/e-run ".$input2);break;
		case "debug": system($path."/e-debug ".$input2);break;
		case "stop": system($path."/e-stop");break;
		case "make": system($path."/e-make");break;
		case "build": system($path."/e-build ".$input2);break;
		case "clean": system($path."/e-clean ".$input2);break;
		case "ping": system($path."/e-ping");break;
		case "edit": system($path."/e-edit ".$input2);break;
		case "echo": system($path."/e-echo");break;
		case "guvc": system($path."/e-guvc");break;
		case "set":
			switch($input2){
				case "time": system($path."/e-time");break;
				
				// -------------------------------- //
				case "vision":
				case "kepala":
				case "capture":
				case "camera":
				case "ball":
				case "calibration":
				case "focus": system($path."/e-setting ".$input2);break;
				// -------------------------------- //
				
				case "server": system($path."/e-server");break;
				
				// -------------------------------- //
				case "dark":
				case "light": system($path."/e-vm_calibrate ".$input2);break;
				// -------------------------------- //
				
				case "ip": system($path."/e-ip ");break;
				case "net": system($path."/e-net");break;
				default: system("cat $path/help-text");break;
			}
		break;
		default: system("cat $path/help-text");break;
	}
} else echo "Nama robot $remote tidak ada\n";
