#!/usr/bin/php
<?php
if(isset($argv[1])){
	$remote = $argv[1];
	if($remote=="krsbi" || $remote=="robocup"){
		$file = fopen("platform.ini",'w');
		if($remote=="krsbi")fwrite($file,"env");
		if($remote=="robocup")fwrite($file,"envr");
		fclose($file);
		echo "\033[1mSuccessfully switched to $remote platform.\n\033[0m";
	}else{
		echo "\033[1mFailed to switch platform.\n\033[0m";
	}
}else{
	echo "\033[1mInsert platform name.\n\n\033[0m";
	echo "Options:\n";
	echo "usage:\tplatform krsbi\t\t- For playing in KRSBI 2019\n";
	echo "usage:\tplatform robocup\t- For playing in ROBOCUP 2019\n";
}