#!/usr/bin/php
<?php
// Jika ada argumen yang dimasukan oleh user
if(isset($argv[1])) {
	// Jika argumen ke satu sesuai nama platform yang ada
	if($argv[1]=="krsbi" || $argv[1]=="robocup"){
		// Buka file platform.ini dengan mode write (tulis)
		$file = fopen("platform.ini",'w');

		// Tulis nama platform pada argumen ke satu ke $file
		fwrite($file, $argv[1]);

		// Tutup $file
		fclose($file);
		echo "Berhasil berganti platform ke $argv[1].\n";
	} else echo "Platform tidak dikenali. (krsbi | robocup)\n";
} else echo "Masukan nama platform. (krsbi | robocup)\n";