#!/usr/bin/php
<?php
// Jika ada argumen yang dimasukan oleh user
if(isset($argv[1])){
	// Jika argumen ke satu sesuai nama robot yang ada
	if(
		$argv[1] == "huda" ||
		$argv[1] == "bambang" ||
		$argv[1] == "bejo" ||
		$argv[1] == "slamet" ||
		$argv[1] == "umar"
	) {
		// Buka file myrobot.ini dengan mode write (tulis)
		$file = fopen("myrobot.ini",'w');

		// Tulis nama robot pada argumen ke satu ke $file
		fwrite($file,$argv[1]);

		// Tutup $file
		fclose($file);
		echo "$argv[1] sekarang adalah robot yang dipilih.\n";
	} else echo "Nama robot tidak ada. (huda | bambang | bejo | slamet | umar)\n";
} else echo "Masukan nama robot. (huda | bambang | bejo | slamet | umar)\n";
